networks:
  davi_network:
    external: true

services:
  app:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./requirements.txt:/code/requirements.txt
      - ./uploads:/app/uploads
      - /var/opt/DAVI_backend/uploads:/var/opt/DAVI_backend/uploads
      - ./output:/code/output
      - /var/opt/DAVI_backend/output/highlighted:/code/output/highlighted

    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/davi_db
      - DB_NAME=davi_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - davi_network

  mongodb:
    image: mongo:6.0
    container_name: davi_mongodb
    restart: always
    # ports:
    #   - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - default
